routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => '/',
    'as' => 'admin.',
    'middleware' => 'auth'], function () {

    Route::group(['middleware' => 'admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('/category', 'CategoryController');
        Route::resource('/product', 'ProductController');
        Route::resource('/order', 'OrderController');
        Route::resource('/user', 'UserController');
        Route::resource('/client', 'ClientController');
    });
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('/category', 'CategoryController');
    Route::resource('/product', 'ProductController');
});

Auth::routes();

resources/views/layouts/parts/aside.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('admin.dashboard') }}" class="brand-link">
        <span class="brand-text font-weight-light ml-5 pl-3">M-shop</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="/admin-style/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="{{ route('admin.user.show', auth()->user()->id) }}" class="d-block">{{ auth()->user()->name }}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            @include('layouts.parts.menu')
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/layouts/parts/css.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>{{ config('app.name') }} | @yield('title')</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @livewireStyles
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="/admin-style/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/admin-style/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <style>
        .invalid-feedback {
            display: block;
        }
    </style>
</head>

resources/views/layouts/parts/footer.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
        <h5>Title</h5>
        <p>Sidebar content</p>
    </div>
</aside>
<!-- /.control-sidebar -->

<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2019 <a href="{{ route('admin.dashboard') }}">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

resources/views/layouts/parts/js.blade.php
<!-- jQuery -->
<script src="/admin-style/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/admin-style/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<!-- AdminLTE App -->
<script src="/admin-style/dist/js/adminlte.min.js"></script>
<script src="{{ asset('js/app.js') }}"></script>
@livewireScripts

resources/views/layouts/parts/menu.blade.php
<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <li class="nav-item">
        <a href="{{ route('admin.dashboard') }}"
            class="nav-link {{ Route::currentRouteName() == 'admin.dashboard' ? 'active' : '' }}">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
                Dashboard
            </p>
        </a>
    </li>
    <li class="nav-item">
        <a href="{{ route('admin.category.index') }}"
            class="nav-link {{ Route::currentRouteName() == 'admin.category.index' ? 'active' : '' }}">
            <i class="nav-icon fas fa-list-alt"></i>
            <p>
                Categories
            </p>
        </a>
    </li>
    <li class="nav-item">
        <a href="{{ route('admin.product.index') }}"
            class="nav-link {{ Route::currentRouteName() == 'admin.product.index'? 'active' : '' }}">
            <i class="nav-icon fab fa-product-hunt"></i>
            <p>
                Products
            </p>
        </a>
    </li>
    @if (auth()->user()->is_admin)
    <li class="nav-item">
        <a href="{{ route('admin.order.index') }}"
            class="nav-link {{ Route::currentRouteName() == 'admin.order.index'? 'active' : '' }}">
            <i class="nav-icon fas fa-shopping-cart"></i>
            <p>
                Orders
            </p>
        </a>
    </li>
    <li class="nav-item">
        <a href="{{ route('admin.user.index') }}"
            class="nav-link {{ Route::currentRouteName() == 'admin.user.index'? 'active' : '' }}">
            <i class="nav-icon fas fa-users"></i>
            <p>
                Users
            </p>
        </a>
    </li>
    <li class="nav-item">
        <a href="{{ route('admin.client.index') }}"
            class="nav-link {{ Route::currentRouteName() == 'admin.client.index'? 'active' : '' }}">
            <i class="nav-icon fas fa-handshake"></i>
            <p>
                Clients
            </p>
        </a>
    </li>
    @endif
</ul>

resources/views/layouts/parts/nav.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{ route('admin.dashboard') }}" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <form method="POST" action="{{ route('logout') }}">
                @csrf
                <button type="submit" class="btn nav-link">Logout</button>
            </form>

        </li>
    </ul>
</nav>
<!-- /.navbar -->