routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => '/',
    'as' => 'admin.',
    'middleware' => 'auth'], function () {

    Route::group(['middleware' => 'admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('/category', 'CategoryController');
        Route::resource('/product', 'ProductController');
        Route::resource('/order', 'OrderController');
        Route::resource('/user', 'UserController');
        Route::resource('/client', 'ClientController');
    });
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('/category', 'CategoryController');
    Route::resource('/product', 'ProductController');
});

Auth::routes();

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model {
    use SoftDeletes;
    protected $fillable = [
        'date',
        'client_id',
        'user_id',
        'total',
    ];

    public function client() {
        return $this->belongsTo(Client::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function products() {
        return $this->belongsToMany(Product::class,
            'order_details',
            'order_id',
            'product_id')
            ->withPivot(['price', 'quantity', 'total_price'])
            ->withTimestamps()->withTrashed();
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Http\Requests\OrderRequest;
use App\Order;
use App\Product;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $total = DB::table('orders')->where('deleted_at', null)->sum('total');
        return view('admin.order.index', [
            'total' => $total,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.order.createForm', [
            'clients' => Client::get([
                'id',
                'name',
            ]),
            'products' => Product::get([
                'id',
                'name',
                'price',
            ]),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrderRequest $request)
    {
        $request->merge([
            'user_id' => $request->user()->id,
        ]);
        $products = $request->products;

        $productIds = [];

        $total = 0;

        $orderDetails = [];

        foreach ($products as $product) {
            $InventoryQuantity = DB::table('products')
                ->where('id', $product['product_id'])
                ->get('quantity')->first()->quantity;

            $productIds[] = $product['product_id'];

            $productPrice = $product['price'];

            $productQuantity = $product['quantity'];

            if ($InventoryQuantity < $productQuantity) {
                $error = ['invalid.quantity' => 'The inventory quantity of product ' . $product['product_id'] . ' is less than the ordered quantity'];
                return redirect()->back()->withErrors($error)->withInput();
            }

            $productTotalPrice = $productPrice * $productQuantity;

            $total += $productTotalPrice;

            $orderDetails[] = [
                'product_id' => $product['product_id'],
                'quantity' => $productQuantity,
                'price' => $productPrice,
                'total_price' => $productTotalPrice,
            ];
        }

        if (count($productIds) != count(array_unique($productIds))) {
            $error = ['products.duplicate' => 'duplicated Product'];
            return redirect()->back()->withErrors($error)->withInput();
        }

        $order = $request->all();

        $order['total'] = $total;

        $order = Order::create($order);

        $order->products()->attach($orderDetails);

        foreach ($products as $product) {
            $InventoryQuantity = DB::table('products')
                ->where('id', $product['product_id'])
                ->get('quantity')->first()->quantity;

            $editInvetoryQuantity = $InventoryQuantity - $product['quantity'];

            DB::table('products')->where('id', $product['product_id'])
                ->update(['quantity' => $editInvetoryQuantity]);
        }

        return redirect(route('admin.order.show', [$order]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        return view('admin.order.show', [
            'order' => $order,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('admin.order.editForm', [
            'clients' => Client::get([
                'id',
                'name',
            ]),
            // 'products' => Product::get([
            //     'id',
            //     'name',
            //     'price',
            // ]),
            'products' => DB::table('products')->get(),
            // 'products' => $order->products,
            'order' => $order,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(OrderRequest $request, Order $order)
    {
        $oldProducts = $order->products;
        $request->merge([
            'user_id' => $request->user()->id,
        ]);
        $products = $request->products;

        $productIds = [];

        $total = 0;

        foreach ($products as $product) {
            $InventoryQuantity = DB::table('products')
                ->where('id', $product['product_id'])
                ->get('quantity')->first()->quantity;

            $productIds[] = $product['product_id'];

            $productPrice = $product['price'];

            $productQuantity = $product['quantity'];

            if ($InventoryQuantity < $productQuantity) {
                $error = ['invalid.quantity' => 'The inventory quantity of product ' . $product['product_id'] . ' is less than the ordered quantity'];
                return redirect()->back()->withErrors($error)->withInput();
            }

            $productTotalPrice = $productPrice * $productQuantity;

            $total += $productTotalPrice;
        }

        if (count($productIds) != count(array_unique($productIds))) {
            $error = ['products.duplicate' => 'duplicated Product'];
            return redirect()->back()->withErrors($error)->withInput();
        }

        $order['total'] = $total;

        $order->products()->sync($request->get('products'));

        $order->update($request->all());

        foreach ($oldProducts as $product) {

            $oldProductQuantity = $product->getOriginal('pivot_quantity');

            $newProductQuantity = DB::table('order_details')
                ->where(['order_id' => $order->id, 'product_id' => $product->getOriginal('id')])
                ->get('quantity')->first()->quantity;

            if ($newProductQuantity != $oldProductQuantity) {
                $quantityDifference = $newProductQuantity - $oldProductQuantity;

                $InventoryQuantity = DB::table('products')->where('id', $product->getOriginal('id'))->get('quantity')->first()->quantity;

                $editInvetoryQuantity = $InventoryQuantity - $quantityDifference;

                DB::table('products')->where('id', $product->getOriginal('id'))
                    ->update(['quantity' => $editInvetoryQuantity]);
            }
        }

        return redirect(route('admin.order.show', $order));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $order->delete();
        return redirect(route('admin.order.index'));
    }
}

app/Http/Livewire/OrderTable.php
<?php

namespace App\Http\Livewire;

use App\Order;
use Kdion4891\LaravelLivewireTables\Column;
use Kdion4891\LaravelLivewireTables\TableComponent;

class OrderTable extends TableComponent {
    public $table_class = 'table-hover table-striped';
    public $thead_class = 'thead-dark';
    public $header_view = 'admin.order.table-header';
    public $checkbox = false;
    public $sort_attribute = 'id';
    public $sort_direction = 'asc';

    public function mount() {
        $this->setTableProperties();

        if (isset($_GET['limit'])) {
            if ($_GET['limit'] == 10) {
                $num = 10;
                $this->per_page = $num;
            } elseif ($_GET['limit'] == 25) {
                $num = 25;
                $this->per_page = $num;
            } elseif ($_GET['limit'] == 5) {
                $num = 5;
                $this->per_page = $num;
            }
        } else {
            $num = 5;
            $this->per_page = $num;
        }

        return $this->per_page;
    }

    public $per_page;

    public function query() {
        return Order::query()->with(['client', 'products']);
    }

    public function columns() {
        return [
            Column::make('#', 'id')->searchable()->sortable(),
            Column::make('Client Name', 'client.name')->searchable(),
            Column::make('Total_amount $', 'total')->searchable(),
            Column::make('Created At', 'date')->searchable(),
            Column::make('Actions')->view('admin.order.table-actions'),
        ];
    }
}

resources/views/admin/order/index.blade.php
@extends('layouts.app')

@section('title', 'Orders')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Order Page</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Admin</a></li>
                        <li class="breadcrumb-item active">Order Page</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="card card-body">
                    @livewire('order-table')
                    <div>
                        <h1>Total Incom : {{ $total }} $</h1>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

@section('js')
<script>
    $(document).on('click','.delete',function (e) {
        // alert('test');
        e.preventDefault();
        Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
    }).then((result) => {

        $.ajax({
            type: "POST",
            url: $(this).data('url'),
            data: {
                _method:'DELETE',
                _token: '{{csrf_token()}}'
                },
                // dataType: "dataType",
                success: function (response) {
                    if (result.isConfirmed) {

                        Swal.fire({
                            // position: 'center',
                            icon: 'success',
                            title: 'Item Deleted',
                            showConfirmButton: false,
                            timer: 100000
                        });
                    e.preventDefault();
                    location.reload();

                }}
            });
        })
    })


    $(document).on('change','#inlineFormCustomSelect',function () {
        $("#myForm").submit();
    })
</script>
@endsection

resources/views/admin/order/show.blade.php
@extends('layouts.app')

@section('title', 'Show Order')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Show Order</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Admin</a></li>
                            <li class="breadcrumb-item active"><a href="{{ route('admin.order.index') }}">Order
                                    Page</a></li>
                            <li class="breadcrumb-item active">Show Order</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        <h2>Client Name : {{ $order->client->name }}</h2>
                        <h2>User Name : {{ $order->user->name }}</h2>
                        <div class="overflow-auto">
                            <table class="table table-bordered text-center">
                                <thead class="bg-dark text-light">
                                    <tr>
                                        <th>Product Name</th>
                                        <th>Price ($)</th>
                                        <th>quantity</th>
                                        <th>Total Price ($)</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                @foreach ($order->products as $product)
                                    <tbody>
                                        <td>{{ $product->name }}</td>
                                        <td>{{ $product->price }}</td>
                                        <td>{{ $product->pivot->quantity }}</td>
                                        <td>{{ $product->pivot->total_price }}</td>
                                        @if ($product->deleted_at)
                                            <td>{{ $product->name }} has been deleted</td>
                                        @else
                                            <td><a class="btn btn-outline-info"
                                                    href="{{ route('admin.product.show', $product->id) }}">Show Product</a>
                                            </td>
                                        @endif
                                    </tbody>
                                @endforeach
                            </table>
                        </div>
                        <h1 class="mt-2">Total order Price : {{ $order->total }} $</h1>
                    </div>
                </div>
                <a href="{{ route('admin.order.edit', $order) }}" class="btn btn-outline-dark">Edit</a>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/order/table-actions.blade.php
<a href="{{ route('admin.order.show', $model->id) }}" class="btn btn-outline-info">Show</a>
@if (auth()->user()->is_admin)
<a href="{{ route('admin.order.edit', $model->id) }}" class="btn btn-outline-dark">Edit</a>
<button type="button" class="btn btn-outline-danger delete"
    data-url="{{ route('admin.order.destroy', $model->id) }}">Delete</button>
@endif

resources/views/admin/order/table-header.blade.php
<div class="row">
    <form class="text-left d-block" id="myForm">
        <div class="form-row align-items-center">
            <div class="col-auto mr-3">
                <label class="mr-sm-2 sr-only" for="inlineFormCustomSelect">Sort</label>
                <select class="custom-select mr-sm-2 d-block" id="inlineFormCustomSelect" name="limit">
                    <option value=" 5" {{ Request::get('limit') == 5?'selected' : '' }}>5</option>
                    <option value="10" {{ Request::get('limit') == 10? 'selected' : '' }}>10</option>
                    <option value="25" {{ Request::get('limit') == 25? 'selected' : '' }}>25</option>
                </select>
            </div>
        </div>
    </form>
    @if (auth()->user()->is_admin)
    <div class="" style="margin-bottom: -3%">
        <a href="{{ route('admin.order.create') }}" class="btn btn-success">Create New Order</a>
    </div>
    @endif
</div>