routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => '/',
    'as' => 'admin.',
    'middleware' => 'auth'], function () {

    Route::group(['middleware' => 'admin'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('/category', 'CategoryController');
        Route::resource('/product', 'ProductController');
        Route::resource('/order', 'OrderController');
        Route::resource('/user', 'UserController');
        Route::resource('/client', 'ClientController');
    });
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('/category', 'CategoryController');
    Route::resource('/product', 'ProductController');
});

Auth::routes();

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model {
    use SoftDeletes;
    protected $fillable = [
        'name',
        'description',
        'price',
        'category_id',
        'quantity',
        'user_id',
        'reorder_point',
        'created_at',
    ];

    public function category() {
        return $this->belongsTo(Category::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\ProductRequest;
use App\Product;
use App\User;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::get(['name', 'quantity'])->where('quantity', '<=', 5)->all();

        return view('admin.product.index', [
            'products' => $products
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->permissionHandel();
        return view('admin.product.create', [
            'categories' => Category::get([
                'id',
                'name',
            ]),
            'users' => User::get([
                'id',
                'name',
            ]),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $product = Product::create($request->all());
        return redirect(route('admin.product.show', $product));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('admin.product.show', [
            'product' => $product,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $this->permissionHandel();
        return view('admin.product.edit', [
            'product' => $product,
            'users' => User::get([
                'id',
                'name',
            ]),
            'categories' => Category::get([
                'id',
                'name',
            ]),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {
        $product->update($request->all());
        return redirect(route('admin.product.show', $product));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $this->permissionHandel();
        $product->delete();
        return redirect(route('admin.product.index'));
    }

    // public function imageUpload(Product $product) {
    //     return view('admin.product.show', $product);
    // }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function imageUploadPost(Request $request) {
    //     $request->validate([
    //         'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
    //     ]);

    //     $imageName = time() . '.' . $request->image->extension();

    //     $request->image->move(public_path('images'), $imageName);

    //     return back()
    //         ->with('success', 'You have successfully upload image.')
    //         ->with('image', $imageName);
    // }

    private function permissionHandel()
    {
        if (!(auth()->user()->is_admin)) {
            abort(403);
        }
    }
}

app/Http/Livewire/ProductTable.php
<?php

namespace App\Http\Livewire;

use App\Product;
use Kdion4891\LaravelLivewireTables\Column;
use Kdion4891\LaravelLivewireTables\TableComponent;

class ProductTable extends TableComponent {
    public $table_class = 'table-hover table-striped';
    public $thead_class = 'thead-dark';
    public $header_view = 'admin.product.table-header';
    public $checkbox = false;
    public $sort_attribute = 'id';
    public $sort_direction = 'asc';

    public function mount() {
        $this->setTableProperties();

        if (isset($_GET['limit'])) {
            if ($_GET['limit'] == 10) {
                $num = 10;
                $this->per_page = $num;
            } elseif ($_GET['limit'] == 25) {
                $num = 25;
                $this->per_page = $num;
            } elseif ($_GET['limit'] == 5) {
                $num = 5;
                $this->per_page = $num;
            }
        } else {
            $num = 5;
            $this->per_page = $num;
        }

        return $this->per_page;
    }

    public $per_page;

    public function query() {
        return Product::query()->with(['category', 'user']);
    }

    public function columns() {
        return [
            Column::make('#', 'id')->searchable()->sortable(),
            Column::make('Product Name', 'name')->searchable(),
            Column::make('Product Description', 'description')->searchable(),
            Column::make('Product Price', 'price')->searchable(),
            Column::make('Quantity', 'quantity')->searchable(),
            Column::make('Category Name', 'category.name')->searchable(),
            Column::make('Created By', 'user.name')->searchable(),
            Column::make('Created at', 'created_at')->searchable(),
            Column::make('Actions')->view('admin.product.table-actions'),
        ];
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.app')

@section('title', 'Create New Product')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Create Product</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Admin</a></li>
                        <li class="breadcrumb-item active"><a href="{{ route('admin.product.index') }}">Product
                                Page</a></li>
                        <li class="breadcrumb-item active">Create Product</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="card card-body">
                    <form action="{{ route('admin.product.store') }}" method="POST">
                        @include('admin.product.form')
                        <button type="submit" class="btn btn-success">Save</button>
                    </form>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Product')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Edit Product</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Admin</a></li>
                        <li class="breadcrumb-item active"><a href="{{ route('admin.product.index') }}">Product
                                Page</a></li>
                        <li class="breadcrumb-item active">Edit Product</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="card card-body">
                    <form action="{{ route('admin.product.update', $product) }}" method="POST">
                        @method('PUT')
                        @include('admin.product.form')
                        <button type="submit" class="btn btn-success">Update</button>
                    </form>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

resources/views/admin/product/form.blade.php
@csrf
<div class="form-group">
    <label for="user_id">User</label>
    <select name="user_id" id="user_id" class="form-control">
        <option value="">Not Set</option>
        @foreach ($users as $user)
        @if (isset($product) && $user->id == $product->user_id)
        <option value="{{ $user->id }}" selected>{{ $user->name }}</option>
        @else
        <option value="{{ $user->id }}">{{ $user->name }}</option>
        @endif
        @endforeach
        @error('user_id')
        <span class="invalid-feedback" role="alert">
            <strong class="text-danger">{{ $message }}</strong>
        </span>
        @enderror
    </select>
</div>
<div class="form-group">
    <label for="category_id">Category</label>
    <select name="category_id" id="category_id" class="form-control">
        <option value="">Not Set</option>
        @foreach ($categories as $category)
        @if (isset($product) && $category->id == $product->category_id)
        <option value="{{ $category->id }}" selected>{{ $category->name }}</option>
        @else
        <option value="{{ $category->id }}">{{ $category->name }}</option>
        @endif
        @endforeach
        @error('category_id')
        <span class="invalid-feedback" role="alert">
            <strong class="text-danger">{{ $message }}</strong>
        </span>
        @enderror
    </select>
</div>
<div class="form-group">
    <label for="name">Name</label>
    <input type="text" name="name" class="form-control" value="{{ isset($product) ? $product->name : '' }}">
    @error('name')
    <span class="invalid-feedback" role="alert">
        <strong class="text-danger">{{ $message }}</strong>
    </span>
    @enderror
</div>
<div class="form-group">
    <label for="description">Description</label>
    <textarea name="description" id="description" cols="30" rows="10"
        class="form-control">{{ isset($product) ? $product->description : '' }}</textarea>
    @error('description')
    <span class="invalid-feedback" role="alert">
        <strong class="text-danger">{{ $message }}</strong>
    </span>
    @enderror
</div>
<div class="form-group">
    <label for="price">Price</label>
    <input type="number" name="price" class="form-control" value="{{ isset($product) ? $product->price : '' }}">
    @error('price')
    <span class="invalid-feedback" role="alert">
        <strong class="text-danger">{{ $message }}</strong>
    </span>
    @enderror
</div>
<div class="form-group">
    <label for="quantity">Quantity</label>
    <input type="number" name="quantity" class="form-control" value="{{ isset($product) ? $product->quantity : '' }}">
    @error('quantity')
    <span class="invalid-feedback" role="alert">
        <strong class="text-danger">{{ $message }}</strong>
    </span>
    @enderror
</div>
{{-- <form action="{{ route('admin.image.upload.post') }}" method="POST" enctype="multipart/form-data">
@csrf

<div class="col-md-6">
    <input type="file" name="image" class="form-control">
</div>
@if ($errors->first('image'))
<span class="text-danger">
    {{ $errors->first('image') }}
</span>
@endif
<div class="col-md-6">
    <button type="submit" class="btn btn-success d-block">Save</button>
</div>
</form> --}}

resources/views/admin/product/index.blade.php
@extends('layouts.app')

@section('title', 'Products')

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Product Page</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Admin</a></li>
                            <li class="breadcrumb-item active">Product Page</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="card card-body">
                        @livewire('product-table')
                    </div>
                    @if (!empty($products))
                        <div class="card card-body">
                            <h1>Products have less than 5 items</h1>
                            @foreach ($products as $product)
                                <h3>Product : <strong>{{ $product->name }}</strong> has <strong
                                        class="text-danger">{{ $product->quantity }}</strong>
                                    @if ($product->quantity == 1 || $product->quantity == 0)
                                        item
                                    @else
                                        items
                                    @endif
                                </h3>
                            @endforeach

                        </div>
                    @endif
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection
@section('js')
    <script>
        $(document).on('click', '.delete', function(e) {
            // alert('test');
            e.preventDefault();
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {

                $.ajax({
                    type: "POST",
                    url: $(this).data('url'),
                    data: {
                        _method: 'DELETE',
                        _token: '{{ csrf_token() }}'
                    },
                    // dataType: "dataType",
                    success: function(response) {
                        if (result.isConfirmed) {

                            Swal.fire({
                                // position: 'center',
                                icon: 'success',
                                title: 'Item Deleted',
                                showConfirmButton: false,
                                timer: 100000
                            });
                            e.preventDefault();
                            location.reload()
                        }
                    }
                });
            })
        })


        $(document).on('change', '#inlineFormCustomSelect', function() {
            $("#myForm").submit();
        })

    </script>
@endsection

resources/views/admin/product/show.blade.php
@extends('layouts.app')

@section('title', 'Show Product')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Show Product</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Admin</a></li>
                        <li class="breadcrumb-item active"><a href="{{ route('admin.product.index') }}">Product
                                Page</a></li>
                        <li class="breadcrumb-item active">Show Product</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="card card-body">
                    <h5 class="card-header">{{ $product->name }}</h5>
                    <div class="card-body">
                        @if ($product->user)
                        <h5 class="card-title">Created by : {{ $product->user->name }}</h5>
                        @endif
                        <br>
                        @if ($product->category)
                        <h5 class="card-title">Category Name : <a
                                href="{{ route('admin.category.show', $product->category) }}">{{ $product->category->name }}</a>
                        </h5>
                        @endif
                        <p class="card-text">Description : {{ $product->description }}</p>
                        <p class="card-text">Created at : {{ $product->updated_at }}</p>
                        @if (auth()->user()->is_admin)
                        <a href="{{ route('admin.product.edit', $product) }}" class="btn btn-primary">Edit</a>
                        @endif
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

resources/views/admin/product/table-actions.blade.php
<a href="{{ route('admin.product.show', $model->id) }}" class="btn btn-outline-info">Show</a>
@if (auth()->user()->is_admin)
<a href="{{ route('admin.product.edit', $model->id) }}" class="btn btn-outline-dark">Edit</a>
<button type="button" class="btn btn-outline-danger delete"
    data-url="{{ route('admin.product.destroy', $model->id) }}">Delete</button>
@endif

resources/views/admin/product/table-header.blade.php
<div class="row">
    <form class="text-left d-block" id="myForm">
        <div class="form-row align-items-center">
            <div class="col-auto mr-3">
                <label class="mr-sm-2 sr-only" for="inlineFormCustomSelect">Sort</label>
                <select class="custom-select mr-sm-2 d-block" id="inlineFormCustomSelect" name="limit">
                    <option value=" 5" {{ Request::get('limit') == 5?'selected' : '' }}>5</option>
                    <option value="10" {{ Request::get('limit') == 10? 'selected' : '' }}>10</option>
                    <option value="25" {{ Request::get('limit') == 25? 'selected' : '' }}>25</option>
                </select>
            </div>
        </div>
    </form>
    @if (auth()->user()->is_admin)
    <div class="" style="margin-bottom: -3%">
        <a href="{{ route('admin.product.create') }}" class="btn btn-success">Create New Product</a>
    </div>
    @endif
</div>